image:
  tag: v1.16.5
  # as per doc, https://docs.aws.amazon.com/eks/latest/userguide/eks-ug.pdf
  repository: eu.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler
autoDiscovery:
  clusterName: awesome
  enabled: true
awsRegion: ap-southeast-1
cloudProvider: aws
rbac:
  create: true

serviceMonitor:
  enabled: true
  interval: 10s
  namespace: monitoring
  selector:
    release: prom
